---
- hosts: pihole
  become: true
  tasks:
    - name: Update all installed packages using APT module
      apt: 
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true
      tags:
        - osupdates
    - name: Update pi-hole
      ansible.builtin.command: sudo pihole -up
      tags:
      - holeup